export default {
  search: ['请输入您要搜索的资源控制名称', 'Please Enter the Resource Name'],
  info: ['资源控制列可右键进行更多操作', 'The resource control column can be right-clicked for more operations.'],
  tag: ['分类标签', 'Tag'],
  onlyNav: ['非路由导航', 'Only Nav'],
  routerNav: ['路由导航', 'Router Nav'],
  router: ['路由', 'Router'],
  expand: ['全部展开', 'All Expand'],
  close: ['全部关闭', 'All Close'],
  sort: ['开启排序', 'Open Sort'],
  policyEdit: ['策略编辑', 'Policy Edit'],
  AddResource: ['新增资源', 'Add Resource'],
  readonly: ['只读', 'ReadOnly'],
  readandwrite: ['读写', 'Read & Write'],
  resource_key: ['资源控制键', 'Resource Key'],
  acl_key: ['访问控制键', 'Acl Key'],
  aclPlaceHolder: ['请选择访问控制键', 'Please Select Acl Key'],
  policy: ['策略', 'Policy'],
};
